apiVersion: v1
kind: Pod
items:
# Pod for 'driver' on 192.168.178.50 (for wifi in room 057)
# Pod for 'driver' on 192.168.1.101 (for wifi in room 023)

  - apiVersion: v1
    kind: Pod
    metadata:
      name: on-board-driver
      labels:
        app: driver
    spec:
      hostNetwork: true
      nodeSelector:
        node: "OrangePi"
      containers:
      - name: driver
        image: 131.159.61.158:5000/car_driver_with_time:lsx
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: ROS_DOMAIN_ID
          value: "30"
      - name: controller
        # image: 131.159.61.158:5000/controller_with_time:lsx
        image: 131.159.61.158:5000/controller:fixed_pub_rate
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: ROS_DOMAIN_ID
          value: "30"
      - name: mux
        #image: 131.159.61.158:5000/mux_with_time:lsx
        image: 131.159.61.158:5000/mux_lazy_sub:lsx
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: ROS_DOMAIN_ID
          value: "30"
  
