apiVersion: v1
kind: Pod
items:

# Pod for 'driver' on 192.168.178.50 (for wifi in room 057)
# Pod for 'driver' on 192.168.1.101 (for wifi in room 023)

- apiVersion: v1
  kind: Pod
  metadata:
    name: on-board
    labels:
      app: on-board-app
  spec:
    hostNetwork: true
    nodeSelector:
      node: "OrangePi"
    containers:

    - name: driver
      # image: 131.159.61.158:5000/car_driver_with_time:lsx # image 1: acc and turn sequentially
      image: 131.159.61.158:5000/car_driver_diff_con:lsx # image 2: differential controller, process acc and turn simultaneously
      # image: 131.159.61.158:5000/
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: log-volume
          mountPath: /root/ros2_ws/log/runtime/container

    - name: controller
      # image: 131.159.61.158:5000/controller_with_time:lsx #image 1: publish topic at most effort(1000Hz)
      image: 131.159.61.158:5000/controller:fixed_pub_rate # image 2: publish topic with fixed rate(50Hz)
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: log-volume
          mountPath: /root/ros2_ws/log/runtime/container

    - name: mux
      #image: 131.159.61.158:5000/mux_with_time:lsx #image 1: publish topic with fixed rate
      image: 131.159.61.158:5000/mux_lazy_sub:lsx #image 2: publish topic when received
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: log-volume
          mountPath: /root/ros2_ws/log/runtime/container

    - name: sensor
      image: 131.159.61.158:5000/imu_lidar:lsx
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: log-volume
          mountPath: /root/ros2_ws/log/runtime/container
    
    volumes:
      - name: log-volume
        hostPath:
          path: /home/fantasyyeah/ros2_ws/log/runtime/container 
          type: DirectoryOrCreate

- apiVersion: v1
  kind: Pod
  metadata:
    name: lidar-odometry
    labels:
      app: lidar-odometry
  spec:
    hostNetwork: true
    nodeSelector:
      node: "Computer"
    containers:

    - name: odometry
      image: 131.159.61.158:5000/lidar_odom:lsx # image 1: without log file
      # image: 131.159.61.158:5000/lidar_odom:exp # image 2: preserve log file in volume
      imagePullPolicy: Always
      securityContext:
        privileged: false
      volumeMounts:
        - name: log-volume
          mountPath: /root/ros2_ws/log/runtime/container

    # nav2 without rviz2
    # - name: nav2stack
      # #image: 131.159.61.158:5000/car_nav:lsx #image 1: navigation stack without visulization
      # imagePullPolicy: Always
      # securityContext:
        # privileged: false

    # nav2 with rviz2
    - name: nav2stack
      image: 131.159.61.158:5000/car_nav_rviz2:lsx #image 2: navigation stack with visulization
      # image: 131.159.61.158:5000/car_nav_rviz2:exp #image 2.2: navigation stack with visulization, preserve log file in volume
      imagePullPolicy: Always
      securityContext:
        privileged: false
      env:
        - name: DISPLAY
          value: ":1"
      volumeMounts:
        - name: x11-socket
          mountPath: /tmp/.X11-unix
        - name: log-volume
          mountPath: /root/ros2_ws/log/runtime/container

    volumes:
      - name: x11-socket
        hostPath:
          path: /tmp/.X11-unix
      - name: log-volume
        hostPath:
          path: /home/fantasyyeah/ros2_ws/log/runtime/container 
          type: DirectoryOrCreate



      
